// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# The validation APIs help you validate data. Check if an E-mail address is real. Check if a domain is real. Check up on an IP address, and even where it is located. All this and much more is available in the validation API.
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config =  {}, string serviceUrl = "https://api.cloudmersive.com/validate") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Parse an unstructured input text string into an international, formatted address
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    # 
    # # Deprecated
    @deprecated
    remote isolated function parseAddress(ParseAddressRequest payload, map<string|string[]> headers = {}) returns ParseAddressResponse|error {
        string resourcePath = string `/address/parse`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a street address
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    remote isolated function validateAddress(ValidateAddressRequest payload, map<string|string[]> headers = {}) returns ValidateAddressResponse|error {
        string resourcePath = string `/address/street-address`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Normalize a street address
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    remote isolated function normalizeAddress(ValidateAddressRequest payload, map<string|string[]> headers = {}) returns NormalizeAddressResponse|error {
        string resourcePath = string `/address/street-address/normalize`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a City and State/Province combination, get location information about it
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    remote isolated function validateCity(ValidateCityRequest payload, map<string|string[]> headers = {}) returns ValidateCityResponse|error {
        string resourcePath = string `/address/city`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a state or province, name or abbreviation, get location information about it
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    remote isolated function validateState(ValidateStateRequest payload, map<string|string[]> headers = {}) returns ValidateStateResponse|error {
        string resourcePath = string `/address/state`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a postal code, get location information about it
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    remote isolated function validatePostalCode(ValidatePostalCodeRequest payload, map<string|string[]> headers = {}) returns ValidatePostalCodeResponse|error {
        string resourcePath = string `/address/postal-code`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate and normalize country information, return ISO 3166-1 country codes and country name
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function validateCountry(ValidateCountryRequest payload, map<string|string[]> headers = {}) returns ValidateCountryResponse|error {
        string resourcePath = string `/address/country`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get a list of ISO 3166-1 countries
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function listCountries(map<string|string[]> headers = {}) returns CountryListResult|error {
        string resourcePath = string `/address/country/list`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if a country is a member of the European Union (EU)
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function checkEuMembership(ValidateCountryRequest payload, map<string|string[]> headers = {}) returns ValidateCountryResponse|error {
        string resourcePath = string `/address/country/check-eu-membership`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get the currency of the input country
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function getCountryCurrency(ValidateCountryRequest payload, map<string|string[]> headers = {}) returns ValidateCountryResponse|error {
        string resourcePath = string `/address/country/get-currency`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get the region, subregion and continent of the country
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function getCountryRegion(ValidateCountryRequest payload, map<string|string[]> headers = {}) returns ValidateCountryResponse|error {
        string resourcePath = string `/address/country/get-region`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Gets IANA/Olsen time zones for a country
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function getTimezones(GetTimezonesRequest payload, map<string|string[]> headers = {}) returns GetTimezonesResponse|error {
        string resourcePath = string `/address/country/get-timezones`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Geocode a street address into latitude and longitude
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    remote isolated function geocodeAddress(ValidateAddressRequest payload, map<string|string[]> headers = {}) returns ValidateAddressResponse|error {
        string resourcePath = string `/address/geocode`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Reverse geocode a lattitude and longitude into an address
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input reverse geocoding request 
    # + return - OK 
    remote isolated function reverseGeocodeAddress(ReverseGeocodeAddressRequest payload, map<string|string[]> headers = {}) returns ReverseGeocodeAddressResponse|error {
        string resourcePath = string `/address/geocode/reverse`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get current date and time as of now
    #
    # + headers - Headers to be sent with the request 
    # + return - OK 
    remote isolated function getCurrentDateTime(map<string|string[]> headers = {}) returns DateTimeNowResult|error {
        string resourcePath = string `/date-time/get/now`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get public holidays in the specified country and year
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function getPublicHolidays(GetPublicHolidaysRequest payload, map<string|string[]> headers = {}) returns PublicHolidaysResponse|error {
        string resourcePath = string `/date-time/get/holidays`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Parses a standardized date and time string into a date and time
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function parseStandardDateTime(DateTimeStandardizedParseRequest payload, map<string|string[]> headers = {}) returns DateTimeStandardizedParseResponse|error {
        string resourcePath = string `/date-time/parse/date-time/structured`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Parses a free-form natural language date and time string into a date and time
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input request 
    # + return - OK 
    remote isolated function parseNaturalLanguageDateTime(DateTimeNaturalLanguageParseRequest payload, map<string|string[]> headers = {}) returns DateTimeStandardizedParseResponse|error {
        string resourcePath = string `/date-time/parse/date-time/natural-language`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a domain name
    #
    # + headers - Headers to be sent with the request 
    # + payload - Domain name to check, for example "cloudmersive.com".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function validateDomain(string payload, map<string|string[]> headers = {}) returns CheckResponse|error {
        string resourcePath = string `/domain/check`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a domain name's quality score
    #
    # + headers - Headers to be sent with the request 
    # + payload - Domain name to check, for example "cloudmersive.com" 
    # + return - OK 
    remote isolated function getDomainQualityScore(string payload, map<string|string[]> headers = {}) returns DomainQualityResponse|error {
        string resourcePath = string `/domain/quality-score`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get WHOIS information for a domain
    #
    # + headers - Headers to be sent with the request 
    # + payload - Domain name to check, for example "cloudmersive.com".   The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function getDomainWhois(string payload, map<string|string[]> headers = {}) returns WhoisResponse|error {
        string resourcePath = string `/domain/whois`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a URL syntactically
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL information 
    # + return - OK 
    remote isolated function validateUrlSyntax(ValidateUrlRequestSyntaxOnly payload, map<string|string[]> headers = {}) returns ValidateUrlResponseSyntaxOnly|error {
        string resourcePath = string `/domain/url/syntax-only`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a URL fully
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL request 
    # + return - OK 
    remote isolated function validateUrl(ValidateUrlRequestFull payload, map<string|string[]> headers = {}) returns ValidateUrlResponseFull|error {
        string resourcePath = string `/domain/url/full`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get top-level domain name from URL
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL information 
    # + return - OK 
    remote isolated function getTopLevelDomain(ValidateUrlRequestSyntaxOnly payload, map<string|string[]> headers = {}) returns ValidateUrlResponseSyntaxOnly|error {
        string resourcePath = string `/domain/url/get-top-level-domain`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check a URL for Phishing threats
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL request 
    # + return - OK 
    remote isolated function checkUrlPhishing(PhishingCheckRequest payload, map<string|string[]> headers = {}) returns PhishingCheckResponse|error {
        string resourcePath = string `/domain/url/phishing-threat-check`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if path is a high-risk or vulnerable server administration path
    #
    # + headers - Headers to be sent with the request 
    # + payload - URL or relative path to check, e.g. "/admin/login".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function checkAdminPath(string payload, map<string|string[]> headers = {}) returns IsAdminPathResponse|error {
        string resourcePath = string `/domain/url/is-admin-path`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check a URL for safety threats
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL request 
    # + return - OK 
    remote isolated function checkUrlSafety(UrlSafetyCheckRequestFull payload, map<string|string[]> headers = {}) returns UrlSafetyCheckResponseFull|error {
        string resourcePath = string `/domain/url/safety-threat-check`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check a URL for SSRF threats
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL request 
    # + return - OK 
    remote isolated function checkUrlSsrf(UrlSsrfRequestFull payload, map<string|string[]> headers = {}) returns UrlSsrfResponseFull|error {
        string resourcePath = string `/domain/url/ssrf-threat-check`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check a URL for SSRF threats in batches
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL request as a batch of multiple URLs 
    # + return - OK 
    remote isolated function checkUrlSsrfBatch(UrlSsrfRequestBatch payload, map<string|string[]> headers = {}) returns UrlSsrfResponseBatch|error {
        string resourcePath = string `/domain/url/ssrf-threat-check/batch`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check a URL for HTML embedded SSRF threats
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input URL request 
    # + return - OK 
    remote isolated function checkUrlHtmlSsrf(UrlHtmlSsrfRequestFull payload, map<string|string[]> headers = {}) returns UrlHtmlSsrfResponseFull|error {
        string resourcePath = string `/domain/url/ssrf-threat-check/html-embedded`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate email adddress for syntactic correctness only
    #
    # + headers - Headers to be sent with the request 
    # + payload - Email address to validate, e.g. "support@cloudmersive.com".    The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function validateEmailSyntax(string payload, map<string|string[]> headers = {}) returns AddressVerifySyntaxOnlyResponse|error {
        string resourcePath = string `/email/address/syntaxOnly`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Partially check whether an email address is valid
    #
    # + headers - Headers to be sent with the request 
    # + payload - Email address to validate, e.g. "support@cloudmersive.com".    The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function checkEmailServers(string payload, map<string|string[]> headers = {}) returns AddressGetServersResponse|error {
        string resourcePath = string `/email/address/servers`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Fully validate an email address
    #
    # + headers - Headers to be sent with the request 
    # + payload - Email address to validate, e.g. "support@cloudmersive.com".    The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function validateEmailFully(string payload, map<string|string[]> headers = {}) returns FullEmailValidationResponse|error {
        string resourcePath = string `/email/address/full`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get intelligence on an IP address
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to process, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function getIpIntelligence(string payload, map<string|string[]> headers = {}) returns IPIntelligenceResponse|error {
        string resourcePath = string `/ip/intelligence`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Geolocate an IP address
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to geolocate, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function geolocateIp(string payload, map<string|string[]> headers = {}) returns GeolocateResponse|error {
        string resourcePath = string `/ip/geolocate`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Geolocate an IP address to a street address
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to geolocate, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function geolocateIpToStreetAddress(string payload, map<string|string[]> headers = {}) returns GeolocateStreetAddressResponse|error {
        string resourcePath = string `/ip/geolocate/street-address`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if IP address is a known threat
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to check, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function checkIpThreat(string payload, map<string|string[]> headers = {}) returns IPThreatResponse|error {
        string resourcePath = string `/ip/is-threat`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if IP address is a Tor node server
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to check, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function checkIpTorNode(string payload, map<string|string[]> headers = {}) returns TorNodeResponse|error {
        string resourcePath = string `/ip/is-tor-node`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check if IP address is a Bot client
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to check, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function checkIpBot(string payload, map<string|string[]> headers = {}) returns BotCheckResponse|error {
        string resourcePath = string `/ip/is-bot`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Perform a reverse domain name (DNS) lookup on an IP address
    #
    # + headers - Headers to be sent with the request 
    # + payload - IP address to check, e.g. "55.55.55.55".  The input is a string so be sure to enclose it in double-quotes 
    # + return - OK 
    remote isolated function reverseLookupIp(string payload, map<string|string[]> headers = {}) returns IPReverseDNSLookupResponse|error {
        string resourcePath = string `/ip/reverse-domain-lookup`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Enrich an input lead with additional fields of data
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input lead with known fields set, and unknown fields left blank (null) 
    # + return - OK 
    remote isolated function enrichLead(LeadEnrichmentRequest payload, map<string|string[]> headers = {}) returns LeadEnrichmentResponse|error {
        string resourcePath = string `/lead-enrichment/lead/enrich`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get company information from email address
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input email address lead 
    # + return - OK 
    remote isolated function getCompanyInformation(EmailLead payload, map<string|string[]> headers = {}) returns LeadEnrichmentResponse|error {
        string resourcePath = string `/lead-enrichment/lead/email/company-information`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Parse and validate a full name
    #
    # + headers - Headers to be sent with the request 
    # + payload - Validation request information 
    # + return - OK 
    remote isolated function validateFullName(FullNameValidationRequest payload, map<string|string[]> headers = {}) returns FullNameValidationResponse|error {
        string resourcePath = string `/name/full-name`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a first name
    #
    # + headers - Headers to be sent with the request 
    # + payload - Validation request information 
    # + return - OK 
    remote isolated function validateFirstName(FirstNameValidationRequest payload, map<string|string[]> headers = {}) returns FirstNameValidationResponse|error {
        string resourcePath = string `/name/first`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a last name
    #
    # + headers - Headers to be sent with the request 
    # + payload - Validation request information 
    # + return - OK 
    remote isolated function validateLastName(LastNameValidationRequest payload, map<string|string[]> headers = {}) returns LastNameValidationResponse|error {
        string resourcePath = string `/name/last`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get the gender of a first name
    #
    # + headers - Headers to be sent with the request 
    # + payload - Gender request information 
    # + return - OK 
    remote isolated function getGender(GetGenderRequest payload, map<string|string[]> headers = {}) returns GetGenderResponse|error {
        string resourcePath = string `/name/get-gender`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a code identifier
    #
    # + headers - Headers to be sent with the request 
    # + payload - Identifier validation request information 
    # + return - OK 
    remote isolated function validateIdentifier(ValidateIdentifierRequest payload, map<string|string[]> headers = {}) returns ValidateIdentifierResponse|error {
        string resourcePath = string `/name/identifier`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate phone number (basic)
    #
    # + headers - Headers to be sent with the request 
    # + payload - Phone number to validate in a PhoneNumberValidateRequest object.  Try a phone number such as "1.800.463.3339", and either leave DefaultCountryCode blank or use "US" 
    # + return - OK 
    remote isolated function validatePhoneNumber(PhoneNumberValidateRequest payload, map<string|string[]> headers = {}) returns PhoneNumberValidationResponse|error {
        string resourcePath = string `/phonenumber/basic`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check text input for SQL Injection (SQLI) attacks
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - OK 
    remote isolated function checkSqlInjection(string payload, CheckSqlInjectionHeaders headers = {}) returns SqlInjectionDetectionResult|error {
        string resourcePath = string `/text-input/check/sql-injection`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check and protect multiple text inputs for SQL Injection (SQLI) attacks in batch
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - OK 
    remote isolated function checkSqlInjectionBatch(SqlInjectionCheckBatchRequest payload, map<string|string[]> headers = {}) returns SqlInjectionCheckBatchResponse|error {
        string resourcePath = string `/text-input/check/sql-injection/batch`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check text input for Cross-Site-Scripting (XSS) attacks
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - OK 
    remote isolated function checkXss(string payload, map<string|string[]> headers = {}) returns XssProtectionResult|error {
        string resourcePath = string `/text-input/check/xss`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Protect text input from Cross-Site-Scripting (XSS) attacks through normalization
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - OK 
    remote isolated function protectXss(string payload, map<string|string[]> headers = {}) returns XssProtectionResult|error {
        string resourcePath = string `/text-input/protect/xss`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Check and protect multiple text inputs for Cross-Site-Scripting (XSS) attacks in batch
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - OK 
    remote isolated function checkXssBatch(XssProtectionBatchRequest payload, map<string|string[]> headers = {}) returns XssProtectionBatchResponse|error {
        string resourcePath = string `/text-input/check-and-protect/xss/batch`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Protect html input from Server-side Request Forgery (SSRF) attacks
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing HTML input 
    # + return - OK 
    remote isolated function checkHtmlSsrf(string payload, CheckHtmlSsrfHeaders headers = {}) returns HtmlSsrfDetectionResult|error {
        string resourcePath = string `/text-input/html/check/ssrf`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Protect text input from XML External Entity (XXE) attacks
    #
    # + headers - Headers to be sent with the request 
    # + payload - User-facing text input 
    # + return - OK 
    remote isolated function checkXxe(string payload, CheckXxeHeaders headers = {}) returns XxeDetectionResult|error {
        string resourcePath = string `/text-input/check/xxe`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Protect text input from XML External Entity (XXE) attacks
    #
    # + headers - Headers to be sent with the request 
    # + payload - Batch of text inputs to scan for XXE attacks 
    # + return - OK 
    remote isolated function checkXxeBatch(XxeDetectionBatchRequest payload, map<string|string[]> headers = {}) returns XxeDetectionBatchResponse|error {
        string resourcePath = string `/text-input/check/xxe/batch`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Parse an HTTP User-Agent string, identify robots
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input parse request 
    # + return - OK 
    remote isolated function parseUserAgent(UserAgentValidateRequest payload, map<string|string[]> headers = {}) returns UserAgentValidateResponse|error {
        string resourcePath = string `/useragent/parse`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Validate a VAT number
    #
    # + headers - Headers to be sent with the request 
    # + payload - Input VAT code 
    # + return - OK 
    remote isolated function validateVat(VatLookupRequest payload, map<string|string[]> headers = {}) returns VatLookupResponse|error {
        string resourcePath = string `/vat/lookup`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
