// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# IANA/Olsen time zone
public type Timezone record {
    # UTC offset for this time zone
    @jsondata:Name {value: "BaseUTCOffset"}
    string baseUTCOffset?;
    # The current time (Now) in this time zone
    @jsondata:Name {value: "Now"}
    string now?;
    # Name of the Time Zone
    @jsondata:Name {value: "Name"}
    string name?;
};

# Result of the GetGender operation
public type GetGenderResponse record {
    # Gender for this name; possible values are Male, Female, and Neutral (can be applied to Male or Female)
    @jsondata:Name {value: "Gender"}
    string gender?;
    # True if successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Result of performing a Bot check on an IP address
public type BotCheckResponse record {
    # True if the input IP address is a Bot or Robot, false otherwise
    @jsondata:Name {value: "IsBot"}
    boolean isBot?;
};

# Result of performing a domain quality score operation
public type DomainQualityResponse record {
    # The quality score of the domain name; possible values are 0.0 to 10.0 with 10.0 being the highest and 0.0 being the lowest quality
    @jsondata:Name {value: "DomainQualityScore"}
    decimal domainQualityScore?;
};

# Result of checking a URL for SSRF threats
public type UrlSsrfResponseFull record {
    # Threat level of the URL; possible values are High, Medium, Low and None
    @jsondata:Name {value: "ThreatLevel"}
    string threatLevel?;
    # True if the URL is clean, false if it is at risk of containing an SSRF threat or attack
    @jsondata:Name {value: "CleanURL"}
    boolean cleanURL?;
};

# Input lead contact; fill in known fields to extend them with matched field values
public type LeadEnrichmentRequest record {
    # The person's business email address for the lead
    @jsondata:Name {value: "ContactBusinessEmail"}
    string contactBusinessEmail?;
    # House number of the address of the company for the lead
    @jsondata:Name {value: "CompanyHouseNumber"}
    string companyHouseNumber?;
    # Domain name / website for the lead
    @jsondata:Name {value: "CompanyDomainName"}
    string companyDomainName?;
    # Street name of the address of the company for the lead
    @jsondata:Name {value: "CompanyStreet"}
    string companyStreet?;
    # The person's last name for the lead
    @jsondata:Name {value: "ContactLastName"}
    string contactLastName?;
    # Name of the company for the lead
    @jsondata:Name {value: "CompanyName"}
    string companyName?;
    # Postal Code of the address of the company for the lead
    @jsondata:Name {value: "CompanyPostalCode"}
    string companyPostalCode?;
    # State or Province of the address of the company for the lead
    @jsondata:Name {value: "CompanyStateOrProvince"}
    string companyStateOrProvince?;
    # Country Code (2-letter ISO 3166-1) of the address of the company for the lead
    @jsondata:Name {value: "CompanyCountryCode"}
    string companyCountryCode?;
    # Telephone of the company office for the lead
    @jsondata:Name {value: "CompanyTelephone"}
    string companyTelephone?;
    # VAT number of the company for the lead
    @jsondata:Name {value: "CompanyVATNumber"}
    string companyVATNumber?;
    # The person's first name for the lead
    @jsondata:Name {value: "ContactFirstName"}
    string contactFirstName?;
    # City of the address of the company for the lead
    @jsondata:Name {value: "CompanyCity"}
    string companyCity?;
    # Country of the address of the company for the lead
    @jsondata:Name {value: "CompanyCountry"}
    string companyCountry?;
};

# Result of a validation operation
public type CheckResponse record {
    # True if the domain name was valid, false if it is not
    @jsondata:Name {value: "ValidDomain"}
    boolean validDomain?;
};

# Request to determine if a URL is a safety threat check
public type UrlSafetyCheckRequestFull record {
    # URL to validate
    @jsondata:Name {value: "URL"}
    string uRL?;
};

# Request to parse an address formatted as a string/free text into a structured address
public type ParseAddressRequest record {
    # A mailing address or street address formatted as a single text string; this will be parsed into its components
    @jsondata:Name {value: "AddressString"}
    string addressString?;
    # Optional; indicates how the parsed output should be capitalized; default is Title Case; possible values are: "Uppercase" will set the capitalization to UPPER CASE; "Lowercase" will set the capitalization to lower case; "Titlecase" will set the capitalization to Title Case; and "Originalcase" will preserve the original casing as much as possible
    @jsondata:Name {value: "CapitalizationMode"}
    string capitalizationMode?;
};

# Public holiday occurrence
public type PublicHolidayOccurrence record {
    # Type of the holiday; possible values are: Public, Optional
    @jsondata:Name {value: "HolidayType"}
    string holidayType?;
    # Date of the holiday (start time)
    @jsondata:Name {value: "OccurrenceDate"}
    string occurrenceDate?;
    # True if the holiday is celebrated in all locales in the country, false otherwise
    @jsondata:Name {value: "Nationwide"}
    boolean nationwide?;
    # Name of the holiday in English
    @jsondata:Name {value: "EnglishName"}
    string englishName?;
    # Local name of the holiday
    @jsondata:Name {value: "LocalName"}
    string localName?;
};

# Input to a VAT lookup request
public type VatLookupRequest record {
    # VAT code to lookup; example "CZ25123891"
    @jsondata:Name {value: "VatCode"}
    string vatCode?;
};

# Request to determine if a URL contains HTML-embedded SSRF threats
public type UrlHtmlSsrfRequestFull record {
    # URL to validate
    @jsondata:Name {value: "URL"}
    string uRL?;
};

# Request to validate a last name
public type LastNameValidationRequest record {
    # Last name to process
    @jsondata:Name {value: "LastName"}
    string lastName?;
};

# Result of enumerating available countries
public type CountryListResult record {
    # List of current ISO 3166-1 countries in the world
    @jsondata:Name {value: "Countries"}
    CountryDetails[] countries?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Input parameter to a date time parsing request
public type DateTimeStandardizedParseRequest record {
    # Raw string input of a standard-formatted date and time for parsing
    @jsondata:Name {value: "RawDateTimeInput"}
    string rawDateTimeInput?;
    # Optional: specify the two-letter country code to optimzie date formatting; default is US
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
};

# Input to a batch XSS protection operation
public type XssProtectionBatchRequest record {
    # Multiple items to protect for XSS
    @jsondata:Name {value: "RequestItems"}
    XssProtectionRequestItem[] requestItems?;
};

# Result of validating a URL with syntax only
public type ValidateUrlResponseSyntaxOnly record {
    # True if the URL is valid, false otherwise
    @jsondata:Name {value: "ValidURL"}
    boolean validURL?;
    # The top-level domain name of the URL, e.g. mydomain.com
    @jsondata:Name {value: "TopLevelDomainName"}
    string topLevelDomainName?;
    # Well-formed version of the URL
    @jsondata:Name {value: "WellFormedURL"}
    string wellFormedURL?;
};

# Result of checking a URL for Phishing threats
public type PhishingCheckResponse record {
    # True if the URL is clean, false if it is at risk of containing a Phishing threat or attack
    @jsondata:Name {value: "CleanURL"}
    boolean cleanURL?;
    # Threat type of the Phishing threat; possible values are VerifiedPhishingURL, UnverifiedPhishingURL, or VerifiedPhishingDomain
    @jsondata:Name {value: "ThreatType"}
    string threatType?;
};

# Input to a batch SQL Injection detection operation
public type SqlInjectionCheckBatchRequest record {
    # Multiple items to detect for SQL Injection
    @jsondata:Name {value: "RequestItems"}
    SqlInjectionCheckRequestItem[] requestItems?;
    # Set to Normal to target a high-security SQL Injection detection level with a very low false positive rate; select High to target a very-high security SQL Injection detection level with higher false positives.  Default is Normal (recommended)
    @jsondata:Name {value: "DetectionLevel"}
    string detectionLevel?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Current date and time response
public type DateTimeNowResult record {
    # Current GMT-time-zone date, time, and time zone in standard JSON date format
    @jsondata:Name {value: "NowGmt"}
    string nowGmt?;
    # Current date, time, and time zone in standard JSON date format
    @jsondata:Name {value: "Now"}
    string now?;
    # True if successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Represents the Headers record for the operation: checkXxe
public type CheckXxeHeaders record {
    # Optional: Comma separated list of fully-qualified URLs that will automatically be considered unsafe
    string knownUnsafeUrls?;
    # Optional: Comma separated list of fully-qualified URLs that will automatically be considered safe
    string knownSafeUrls?;
    # Optional: Set to true to allow Internet-based dependency URLs for DTDs and other XML External Entitites, set to false to block.  Default is false
    boolean allowInternetUrls?;
};

# Result of performing a batch XSS protection operation
public type SqlInjectionCheckBatchResponse record {
    # Results from performing a batch SQL Injection detection operation; order is preserved from input data
    @jsondata:Name {value: "ResultItems"}
    SqlInjectionDetectionResult[] resultItems?;
};

# Request to Validate a City and State or Province in a country
public type ValidateCityRequest record {
    # Required: State or province of the address to validate, such as 'California' or 'CA'
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # Optional (recommended); Name of the country, such as 'United States'.  If left blank, and CountryCode is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # Required: City of the address to validate, such as 'San Francisco' or 'London'
    @jsondata:Name {value: "City"}
    string city?;
    # Optional; two-letter country code (Two-letter ISO 3166-1 country code) of the country.  If left blank, and CountryFullName is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
};

public type EmailLead record {
    @jsondata:Name {value: "EmailAddress"}
    string emailAddress?;
};

# Result of validating a state
public type ValidateStateResponse record {
    # True if the address is valid, false otherwise
    @jsondata:Name {value: "ValidState"}
    boolean validState?;
    # If valid; State or province corresponding to the input state name, such as 'CA' or 'California'
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # If the postal code is valid, the degrees latitude of the centroid of the state, null otherwise
    @jsondata:Name {value: "Latitude"}
    decimal latitude?;
    # If the postal code is valid, the degrees longitude of the centroid of the state, null otherwise
    @jsondata:Name {value: "Longitude"}
    decimal longitude?;
};

# Individual item to detect for XXE
public type XxeDetectionRequestItem record {
    # Optional: Set to true to allow Internet-based dependency URLs for DTDs and other XML External Entitites, set to false to block.  Default is false
    @jsondata:Name {value: "AllowInternetUrls"}
    boolean allowInternetUrls?;
    # Optional: Comma separated list of fully-qualified URLs that will automatically be considered safe
    @jsondata:Name {value: "KnownSafeUrls"}
    string[] knownSafeUrls?;
    # Individual input text item to protect from XXE
    @jsondata:Name {value: "InputText"}
    string inputText?;
    # Optional: Comma separated list of fully-qualified URLs that will automatically be considered unsafe
    @jsondata:Name {value: "KnownUnsafeUrls"}
    string[] knownUnsafeUrls?;
};

# Result of checking a URL for HTML-embedded SSRF threats
public type UrlHtmlSsrfResponseFull record {
    # True if the URL is clean, false if it is at risk of containing an SSRF threat or attack
    @jsondata:Name {value: "CleanURL"}
    boolean cleanURL?;
    # HTTP response code from the URL
    @jsondata:Name {value: "HttpResponseCode"}
    int:Signed32 httpResponseCode?;
};

# Represents the Headers record for the operation: checkHtmlSsrf
public type CheckHtmlSsrfHeaders record {
    # Optional: Set to true to allow cid: scheme URLs for email message attachments.  Default is false
    boolean allowCidScheme?;
};

# Result of performing a date time parsing
public type DateTimeStandardizedParseResponse record {
    # Month of the parsed date time result
    @jsondata:Name {value: "Month"}
    int:Signed32 month?;
    # Day of week
    @jsondata:Name {value: "DayOfWeek"}
    string dayOfWeek?;
    # Year of the parsed date time result
    @jsondata:Name {value: "Year"}
    int:Signed32 year?;
    # Minute of the parsed date time result
    @jsondata:Name {value: "Minute"}
    int:Signed32 minute?;
    # Second of the parsed date time result
    @jsondata:Name {value: "Second"}
    int:Signed32 second?;
    # Hour of the parsed date time result (24-hour)
    @jsondata:Name {value: "Hour"}
    int:Signed32 hour?;
    # Result of performing a date time parsing
    @jsondata:Name {value: "ParsedDateResult"}
    string parsedDateResult?;
    # True if successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Day of the parsed date time result
    @jsondata:Name {value: "Day"}
    int:Signed32 day?;
};

# Request to Validate a Postal Code
public type ValidatePostalCodeRequest record {
    # Required: Zip code or postal code of the address to validate, such as '94597'
    @jsondata:Name {value: "PostalCode"}
    string postalCode?;
    # Optional (recommended); Name of the country, such as 'United States'.  If left blank, and CountryCode is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # Optional; two-letter country code (Two-letter ISO 3166-1 country code) of the country.  If left blank, and CountryFullName is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
};

# Result of performing an SQL Injection protection operation
public type SqlInjectionDetectionResult record {
    # True if the input contained SQL Injection attacks, false otherwise
    @jsondata:Name {value: "ContainedSqlInjectionAttack"}
    boolean containedSqlInjectionAttack?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Original input string
    @jsondata:Name {value: "OriginalInput"}
    string originalInput?;
};

# Result of performing a Tor node check on an IP address
public type TorNodeResponse record {
    # True if the input IP address is a Tor exit node, false otherwise
    @jsondata:Name {value: "IsTorNode"}
    boolean isTorNode?;
};

# Request to get time zones for a country
public type GetTimezonesRequest record {
    # Can be the two-letter, three-letter country codes or country name
    @jsondata:Name {value: "CountryCodeOrName"}
    string countryCodeOrName?;
};

# Result of a last name validation operation
public type LastNameValidationResponse record {
    # Possible values are: ValidLastName, ValidUnknownLastName, InvalidSpamInput, InvalidCharacters, InvalidEmpty
    @jsondata:Name {value: "ValidationResult"}
    string validationResult?;
    # True if the validation operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Input parameter to a date time parsing request
public type DateTimeNaturalLanguageParseRequest record {
    # Raw string input of a natural language-formatted date and time for parsing
    @jsondata:Name {value: "RawDateTimeInput"}
    string rawDateTimeInput?;
};

# Result of performing a get public holidays request operation
public type PublicHolidaysResponse record {
    # Public holidays in the requested country and year
    @jsondata:Name {value: "PublicHolidays"}
    PublicHolidayOccurrence[] publicHolidays?;
    # True if successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Result of a partial email address validation
public type AddressGetServersResponse record {
    # Email servers for this email address
    @jsondata:Name {value: "Servers"}
    string[] servers?;
    # True if partial address validation was successufl, false otherwise
    @jsondata:Name {value: "Success"}
    boolean success?;
};

# Result of performing a Reverse Domain (DNS) lookup on an IP address
public type IPReverseDNSLookupResponse record {
    # True if a domain was found, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Host name (fully-qualified) associated with the IP address, if any
    @jsondata:Name {value: "HostName"}
    string hostName?;
};

# Request to validate a first name
public type FirstNameValidationRequest record {
    # First name to process
    @jsondata:Name {value: "FirstName"}
    string firstName?;
};

# User-Agent parse and validation request
public type UserAgentValidateRequest record {
    # The user agent string you wish to parse and validate
    @jsondata:Name {value: "UserAgentString"}
    string userAgentString?;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    # API Key Authentication
    @display {label: "", kind: "password"}
    string apikey;
|};

# Full email addresss validation result
public type FullEmailValidationResponse record {
    # True if the email address is valid overall, false otherwise
    @jsondata:Name {value: "ValidAddress"}
    boolean validAddress?;
    # Email server connected to for verification
    @jsondata:Name {value: "MailServerUsedForValidation"}
    string mailServerUsedForValidation?;
    # True if the syntax of the email address is valid, false otherwise.  This is one component of ValidAddress, but not the only one
    @jsondata:Name {value: "Valid_Syntax"}
    boolean validSyntax?;
    # True if the domain is a catch-all domain name, false otherwise.  Catch-all domain names, while rare, always accept inbound email to ensure they do not lose any potentially useful emails.  Catch-all domain names can occassionally be configured to first accept and store all inbound email, but then later send a bounce email back to the sender after a delayed period of time
    @jsondata:Name {value: "IsCatchallDomain"}
    boolean isCatchallDomain?;
    # True if the email address was verified by the remote server, false otherwise.  This is one component of ValidAddress, but not the only one
    @jsondata:Name {value: "Valid_SMTP"}
    boolean validSMTP?;
    # True if the domain name of the email address is valid, false otherwise.  This is one component of ValidAddress, but not the only one
    @jsondata:Name {value: "Valid_Domain"}
    boolean validDomain?;
    # True if the email domain name is a free provider (typically a free to sign up web email provider for consumers / personal use), false otherwise
    @jsondata:Name {value: "IsFreeEmailProvider"}
    boolean isFreeEmailProvider?;
    # Domain name of the email address
    @jsondata:Name {value: "Domain"}
    string domain?;
    # True if the email address is a disposable email address, false otherwise; these disposable providers are not typically used to receive email and so will have a low likelihood of opening mail sent there
    @jsondata:Name {value: "IsDisposable"}
    boolean isDisposable?;
};

# Result of performing a batch XSS protection operation
public type XssProtectionBatchResponse record {
    # Results from performing a batch XSS protection operation
    @jsondata:Name {value: "ResultItems"}
    XssProtectionResult[] resultItems?;
};

# Result of performing a country validation operation
public type ValidateCountryResponse record {
    # Subregion in which the country is located; possible values are None, NorthernEurope, WesternEurope, SouthernEurope, EasternEurope, CentralAmerica, NorthernAmerica, SouthAmerica, EasternAfrica, MiddleAfrica, NorthernAfrica , SouthernAfrica , WesternAfrica , CentralAsia , EasternAsia , SouthernAsia , SouthEasternAsia , WesternAsia , Southern , Middle , AustraliaandNewZealand , Melanesia , Polynesia , Micronesia , Caribbean,
    @jsondata:Name {value: "Subregion"}
    string subregion?;
    # Two-letter FIPS 10-4 country code
    @jsondata:Name {value: "FIPSTwoLetterCode"}
    string fIPSTwoLetterCode?;
    # Time zones (IANA/Olsen) in the country
    @jsondata:Name {value: "Timezones"}
    Timezone[] timezones?;
    # ISO 4217 currency three-letter code associated with the country
    @jsondata:Name {value: "ISOCurrencyCode"}
    string iSOCurrencyCode?;
    # Full name of the currency
    @jsondata:Name {value: "CurrencyEnglishName"}
    string currencyEnglishName?;
    # Full name of the country
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # Region (continent) in which the country is located; possible values are None, Europe, Americas, Asia, Africa, Oceania
    @jsondata:Name {value: "Region"}
    string region?;
    # Three-letter ISO 3166-1 country code
    @jsondata:Name {value: "ThreeLetterCode"}
    string threeLetterCode?;
    # Two-letter ISO 3166-1 country code
    @jsondata:Name {value: "ISOTwoLetterCode"}
    string iSOTwoLetterCode?;
    # True if successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # True if this country is currently a member of the European Union (EU), false otherwise
    @jsondata:Name {value: "IsEuropeanUnionMember"}
    boolean isEuropeanUnionMember?;
    # Symbol associated with the currency
    @jsondata:Name {value: "CurrencySymbol"}
    string currencySymbol?;
};

# Geolocation result of performing an IP address geolocation operation.  This product includes GeoLite2 data created by MaxMind, available from www.maxmind.com
public type GeolocateResponse record {
    # State/region code of IP address
    @jsondata:Name {value: "RegionCode"}
    string regionCode?;
    # Country name of IP address
    @jsondata:Name {value: "CountryName"}
    string countryName?;
    # State/region of IP address
    @jsondata:Name {value: "RegionName"}
    string regionName?;
    # Zip or postal code of IP address
    @jsondata:Name {value: "ZipCode"}
    string zipCode?;
    # Timezone of IP address
    @jsondata:Name {value: "TimezoneStandardName"}
    string timezoneStandardName?;
    # Latitude of IP address
    @jsondata:Name {value: "Latitude"}
    decimal latitude?;
    # City of IP address
    @jsondata:Name {value: "City"}
    string city?;
    # Two-letter country code of IP address
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
    # Longitude of IP address
    @jsondata:Name {value: "Longitude"}
    decimal longitude?;
};

# Represents the Headers record for the operation: checkSqlInjection
public type CheckSqlInjectionHeaders record {
    # Set to Normal to target a high-security SQL Injection detection level with a very low false positive rate; select High to target a very-high security SQL Injection detection level with higher false positives.  Default is Normal (recommended)
    string detectionLevel?;
};

# Result of performing an XXE threat detection operation
public type HtmlSsrfDetectionResult record {
    # True if the input contained SSRF threats, false otherwise
    @jsondata:Name {value: "ContainedThreats"}
    boolean containedThreats?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Request to validate a phone number
public type PhoneNumberValidateRequest record {
    # Raw phone number string to parse as input for validation
    @jsondata:Name {value: "PhoneNumber"}
    string phoneNumber?;
    # Optional, default country code.  If left blank, will default to "US"
    @jsondata:Name {value: "DefaultCountryCode"}
    string defaultCountryCode?;
};

# Request to validate a full name string
public type FullNameValidationRequest record {
    # Full name to process as a free-form string; supports many components such as First Name, Middle Name, Last Name, Title, Nickname, Suffix, and Display Name
    @jsondata:Name {value: "FullNameString"}
    string fullNameString?;
};

# Individual item to protect for SQL Injection
public type SqlInjectionCheckRequestItem record {
    # Individual input text item to check for SQL Injection
    @jsondata:Name {value: "InputText"}
    string inputText?;
};

# Request to determine if a URL is valid
public type ValidateUrlRequestFull record {
    # URL to validate
    @jsondata:Name {value: "URL"}
    string uRL?;
};

# Request to get the gender from a first name
public type GetGenderRequest record {
    # Input first name (given name) to get the gender of
    @jsondata:Name {value: "FirstName"}
    string firstName?;
    # Optional; the country for this name, possible values are "US", "LY", "NI", "TT", "MK", "KZ", "BO", "UG", "TZ", "CL", "SI", "MA", "RW", "VN", "AW", "CY", "BH", "SG", "ZA", "MU", "BR", "TN", "KH", "US", "TH", "TW", "UY", "DO", "CO", "UA", "QA", "BY", "SN", "SD", "FJ", "LB", "BE", "ML", "LV", "FR", "TM", "NG", "EC", "NO", "SL", "CR", "PA", "GE", "CH", "KR", "RS", "ZM", "FI", "BF", "MC", "AU", "GA", "LS", "RU", "IN", "SE", "LK", "BZ", "MX", "GH", "AF", "TJ", "BN", "DZ", "CM", "GR", "MD", "HN", "AT", "NZ", "SV", "GW", "NA", "AR", "MZ", "PK", "MN", "IQ", "BW", "VE", "PT", "BS", "AL", "TG", "ID", "ET", "CF", "JP", "BB", "PH", "CU", "BD", "AO", "SM", "LC", "ME", "RO",  DANIL"O"", "ES", "EE", "IL", "ZW", "SY", "MW", "LU", "IR", "SC", "NL", "JO", "AM", "DE", "GL", "OM", "DK", "HR", "LI", "TD", "KM", "BA", "GM", "GD", "CA", "CZ", "MR", "ST", "IS", "LR", "IE", "VC", "AE", "KG", "DJ", "TR", "KE", "NE", "UZ", "CN", "GQ", "SK", "BJ", "MG", "BT", "EG", "PL", "IT", "SA", "MY", "CI", "AG", "AD", "KS", "HU", "CG", "KP", "DM", "GN", "GT", "NP", "JM", "LA", "GB", "BG", "HT", "PE", "AZ", "LT", "SZ", "PY", "MT", "VA"
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
};

# Result of performing a batch XXE detection operation
public type XxeDetectionBatchResponse record {
    # Results from performing a batch XSS protection operation
    @jsondata:Name {value: "ResultItems"}
    XxeDetectionResult[] resultItems?;
};

# Result of performing an identifier validation operation
public type ValidateIdentifierResponse record {
    # True if the input identifier is valid, false otherwise
    @jsondata:Name {value: "ValidIdentifier"}
    boolean validIdentifier?;
    # Resulting error from the identifier validation; possible errors are: "InputIsEmpty", "ContainsWhitespace", "ContainsNumbers", "ContainsHyphen", "ContainsUnderscore", "ContainsPeriod", "TooShort", "TooLong", "ContainsSpecialCharacters"
    @jsondata:Name {value: "Error"}
    string 'error?;
};

# Request to determine if a URL is an SSRF threat check
public type UrlSsrfRequestFull record {
    # Top level domains that you do not want to allow access to, e.g. mydomain.com - will block all subdomains as well
    @jsondata:Name {value: "BlockedDomains"}
    string[] blockedDomains?;
    # URL to validate
    @jsondata:Name {value: "URL"}
    string uRL?;
};

# Result of the lead enrichment process
public type LeadEnrichmentResponse record {
    # The person's business email address for the lead
    @jsondata:Name {value: "ContactBusinessEmail"}
    string contactBusinessEmail?;
    # House number of the address of the company for the lead
    @jsondata:Name {value: "CompanyHouseNumber"}
    string companyHouseNumber?;
    # Domain name / website for the lead
    @jsondata:Name {value: "CompanyDomainName"}
    string companyDomainName?;
    # Count of employees at the company (estimated), if available
    @jsondata:Name {value: "EmployeeCount"}
    int:Signed32 employeeCount?;
    # The type of the lead; possible types are Junk (a single individual using a disposable/throwaway email address); Individual (a single individual, typically a consumer, not purchasing on behalf of a business); SmallBusiness (a small business, typically with fewer than 100 employees); MediumBusiness (a medium business, larger than 100 employees but fewer than 1000 employees); Enterprise (a large business with greater than 1000 employees); Business (a business customer of unknown size)
    @jsondata:Name {value: "LeadType"}
    string leadType?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Street name of the address of the company for the lead
    @jsondata:Name {value: "CompanyStreet"}
    string companyStreet?;
    # The person's last name for the lead
    @jsondata:Name {value: "ContactLastName"}
    string contactLastName?;
    # Name of the company for the lead
    @jsondata:Name {value: "CompanyName"}
    string companyName?;
    # Postal Code of the address of the company for the lead
    @jsondata:Name {value: "CompanyPostalCode"}
    string companyPostalCode?;
    # State or Province of the address of the company for the lead
    @jsondata:Name {value: "CompanyStateOrProvince"}
    string companyStateOrProvince?;
    # Country Code (2-letter ISO 3166-1) of the address of the company for the lead
    @jsondata:Name {value: "CompanyCountryCode"}
    string companyCountryCode?;
    # Telephone of the company office for the lead
    @jsondata:Name {value: "CompanyTelephone"}
    string companyTelephone?;
    # VAT number of the company for the lead
    @jsondata:Name {value: "CompanyVATNumber"}
    string companyVATNumber?;
    # The person's first name for the lead
    @jsondata:Name {value: "ContactFirstName"}
    string contactFirstName?;
    # Gender for contact name; possible values are Male, Female, and Neutral (can be applied to Male or Female).  Requires ContactFirstName
    @jsondata:Name {value: "ContactGender"}
    string contactGender?;
    # City of the address of the company for the lead
    @jsondata:Name {value: "CompanyCity"}
    string companyCity?;
    # Country Name of the address of the company for the lead
    @jsondata:Name {value: "CompanyCountry"}
    string companyCountry?;
};

# Result from validating a phone number
public type PhoneNumberValidationResponse record {
    # Internaltional format of the phone number
    @jsondata:Name {value: "InternationalFormat"}
    string internationalFormat?;
    # National format of the phone number
    @jsondata:Name {value: "NationalFormat"}
    string nationalFormat?;
    # User-friendly long name of the country for the phone number
    @jsondata:Name {value: "CountryName"}
    string countryName?;
    # E.164 format of the phone number
    @jsondata:Name {value: "E164Format"}
    string e164Format?;
    # Two digit country code of the phone number
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
    # True if the operation was successful, false if there was an error during validation.  See IsValid for validation result
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Type of phone number; possible values are: FixedLine, Mobile, FixedLineOrMobile, TollFree, PremiumRate, 
    # SharedCost, Voip, PersonalNumber, Pager, Uan, Voicemail, Unknown
    @jsondata:Name {value: "PhoneNumberType"}
    string phoneNumberType?;
    # True if the phone number is valid, false otherwise
    @jsondata:Name {value: "IsValid"}
    boolean isValid?;
};

# Batch operation to perform SSRF threat checks on multiple URLs
public type UrlSsrfRequestBatch record {
    # Input URLs to check for SSRF threats
    @jsondata:Name {value: "InputItems"}
    UrlSsrfRequestFull[] inputItems?;
};

# Result of validating a city
public type ValidateCityResponse record {
    # If valid; State or province corresponding to the input state name, such as 'CA' or 'California'
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # True if the city is valid, false otherwise
    @jsondata:Name {value: "ValidCity"}
    boolean validCity?;
    # If the postal code is valid, the degrees latitude of the centroid of the state, null otherwise
    @jsondata:Name {value: "Latitude"}
    decimal latitude?;
    # If valid, City corresponding to the input postal code, such as 'Walnut Creek'
    @jsondata:Name {value: "City"}
    string city?;
    # If the postal code is valid, the degrees longitude of the centroid of the state, null otherwise
    @jsondata:Name {value: "Longitude"}
    decimal longitude?;
};

# Geolocation street address result
public type GeolocateStreetAddressResponse record {
    # Street address of IP address
    @jsondata:Name {value: "StreetAddress"}
    string streetAddress?;
    # Country name of IP address
    @jsondata:Name {value: "CountryName"}
    string countryName?;
    # State/region of IP address
    @jsondata:Name {value: "RegionName"}
    string regionName?;
    # Zip or postal code of IP address
    @jsondata:Name {value: "ZipCode"}
    string zipCode?;
    # City of IP address
    @jsondata:Name {value: "City"}
    string city?;
    # Two-letter country code of IP address
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
};

# Result of reverse geocoding a street address
public type ReverseGeocodeAddressResponse record {
    # Street address to validate, such as '2950 Buskirk Ave.'
    @jsondata:Name {value: "StreetAddress"}
    string streetAddress?;
    # State or province of the address to validate, such as 'CA' or 'California'
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # Zip code or postal code of the address to validate, such as '94597'
    @jsondata:Name {value: "PostalCode"}
    string postalCode?;
    # Name of the country, such as 'United States'.  Global countries are supported
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # City part of the addrerss to validate, such as 'Walnut Creek'
    @jsondata:Name {value: "City"}
    string city?;
    # Three-letter ISO 3166-1 country code
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
    # True if the address operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Result of parsing an address into its component parts
public type ParseAddressResponse record {
    # The name of the building, house or structure if applicable, such as "Cloudmersive Building 2".  This will often by null
    @jsondata:Name {value: "Building"}
    string building?;
    # The state or province of the address
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # The street number or house number of the address.  For example, in the address "1600 Pennsylvania Avenue NW" the street number would be "1600".  This value will typically be populated for most addresses
    @jsondata:Name {value: "StreetNumber"}
    string streetNumber?;
    # The name of the street or road of the address.  For example, in the address "1600 Pennsylvania Avenue NW" the street number would be "Pennsylvania Avenue NW"
    @jsondata:Name {value: "Street"}
    string street?;
    # The postal code or zip code of the address
    @jsondata:Name {value: "PostalCode"}
    string postalCode?;
    # Country of the address, if present in the address.  If not included in the address it will be null
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # The city of the address
    @jsondata:Name {value: "City"}
    string city?;
    # Two-letter ISO 3166-1 country code
    @jsondata:Name {value: "ISOTwoLetterCode"}
    string iSOTwoLetterCode?;
    # True if the parsing operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Result of performing a get time zones operation
public type GetTimezonesResponse record {
    # Two-letter FIPS 10-4 country code
    @jsondata:Name {value: "FIPSTwoLetterCode"}
    string fIPSTwoLetterCode?;
    # Time zones (IANA/Olsen) in the country
    @jsondata:Name {value: "Timezones"}
    Timezone[] timezones?;
    # Full name of the country
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # Three-letter ISO 3166-1 country code
    @jsondata:Name {value: "ThreeLetterCode"}
    string threeLetterCode?;
    # Two-letter ISO 3166-1 country code
    @jsondata:Name {value: "ISOTwoLetterCode"}
    string iSOTwoLetterCode?;
    # True if successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

public type VatLookupResponse record {
    # For the business address, the street number or house number of the address.  For example, in the address "1600 Pennsylvania Avenue NW" the street number would be "1600".  This value will typically be populated for most addresses
    @jsondata:Name {value: "BusinessStreetNumber"}
    string businessStreetNumber?;
    # For the business address, the city of the address
    @jsondata:Name {value: "BusinessCity"}
    string businessCity?;
    # Name of the business
    @jsondata:Name {value: "BusinessName"}
    string businessName?;
    # For the business address, the name of the building, house or structure if applicable, such as "Cloudmersive Building 2".  This will often by null
    @jsondata:Name {value: "BusinessBuilding"}
    string businessBuilding?;
    # For the business address, the name of the street or road of the address.  For example, in the address "1600 Pennsylvania Avenue NW" the street number would be "Pennsylvania Avenue NW"
    @jsondata:Name {value: "BusinessStreet"}
    string businessStreet?;
    # For the business address, the postal code or zip code of the address
    @jsondata:Name {value: "BusinessPostalCode"}
    string businessPostalCode?;
    # For the business address, the state or province of the address
    @jsondata:Name {value: "BusinessStateOrProvince"}
    string businessStateOrProvince?;
    # Two-letter country code
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
    # For the business address, country of the address, if present in the address.  If not included in the address it will be null
    @jsondata:Name {value: "BusinessCountry"}
    string businessCountry?;
    # VAT number
    @jsondata:Name {value: "VatNumber"}
    string vatNumber?;
    # Business address as a single string
    @jsondata:Name {value: "BusinessAddress"}
    string businessAddress?;
    # True if the VAT code is valid, false otherwise
    @jsondata:Name {value: "IsValid"}
    boolean isValid?;
};

# Input parameter to a country validation request
public type GetPublicHolidaysRequest record {
    # Optional - the year in which to retrieve the holidays; if left blank (0) it will default to the current year
    @jsondata:Name {value: "Year"}
    int:Signed32 year?;
    # Two-letter code (FIPS 10-4 or ISO 3166-1) of the country; if not specified, defaults to United States
    @jsondata:Name {value: "RawCountryInput"}
    string rawCountryInput?;
};

# IP address intelligence result
public type IPIntelligenceResponse record {
    # ISO 4217 currency code for the IP address location
    @jsondata:Name {value: "CurrencyCode"}
    string currencyCode?;
    # True if the IP address is a known Tor exit node, otherwise false
    @jsondata:Name {value: "IsTorNode"}
    boolean isTorNode?;
    # Region (continent) in which the country is located; possible values are None, Europe, Americas, Asia, Africa, Oceania
    @jsondata:Name {value: "RegionArea"}
    string regionArea?;
    # True if the IP address is a known bot, otherwise false
    @jsondata:Name {value: "IsBot"}
    boolean isBot?;
    # True if the IP address is in the European Union, otherwise false
    @jsondata:Name {value: "IsEU"}
    boolean isEU?;
    # Subregion in which the country is located; possible values are None, NorthernEurope, WesternEurope, SouthernEurope, EasternEurope, CentralAmerica, NorthernAmerica, SouthAmerica, EasternAfrica, MiddleAfrica, NorthernAfrica , SouthernAfrica , WesternAfrica , CentralAsia , EasternAsia , SouthernAsia , SouthEasternAsia , WesternAsia , Southern , Middle , AustraliaandNewZealand , Melanesia , Polynesia , Micronesia , Caribbean,
    @jsondata:Name {value: "SubregionArea"}
    string subregionArea?;
    # True if the IP address is a known threat IP, otherwise false
    @jsondata:Name {value: "IsThreat"}
    boolean isThreat?;
    # Returns the location of the IP address
    @jsondata:Name {value: "Location"}
    GeolocateResponse location?;
    # Name of the currency in English
    @jsondata:Name {value: "CurrencyName"}
    string currencyName?;
};

# Result of performing an XXE threat detection operation
public type XxeDetectionResult record {
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # True if the input contained XXE threats, false otherwise
    @jsondata:Name {value: "ContainedXxe"}
    boolean containedXxe?;
};

# Result of a full name validation operation
public type FullNameValidationResponse record {
    # Suffix to the name, e.g. "Jr." or "Sr."
    @jsondata:Name {value: "Suffix"}
    string suffix?;
    # Possible values are: ValidLastName, ValidUnknownLastName, InvalidSpamInput, InvalidCharacters, InvalidEmpty
    @jsondata:Name {value: "ValidationResult_LastName"}
    string validationResultLastName?;
    # The first name (given name)
    @jsondata:Name {value: "FirstName"}
    string firstName?;
    # Possible values are: ValidFirstName, ValidUnknownFirstName, InvalidSpamInput, InvalidCharacters, InvalidEmpty
    @jsondata:Name {value: "ValidationResult_FirstName"}
    string validationResultFirstName?;
    # The full display name of the name
    @jsondata:Name {value: "DisplayName"}
    string displayName?;
    # The person's title (if supplied), e.g. "Mr." or "Ms."
    @jsondata:Name {value: "Title"}
    string title?;
    # The last name (surname)
    @jsondata:Name {value: "LastName"}
    string lastName?;
    # The middle name(s); if there are multiple names they will be separated by spaces
    @jsondata:Name {value: "MiddleName"}
    string middleName?;
    # Nickname (if supplied)
    @jsondata:Name {value: "NickName"}
    string nickName?;
    # True if the validation operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Result of a WHOIS operation
public type WhoisResponse record {
    # Server used to lookup WHOIS information (may change based on lookup)
    @jsondata:Name {value: "WhoisServer"}
    string whoisServer?;
    # Creation date for the record
    @jsondata:Name {value: "CreatedDt"}
    string createdDt?;
    # True if the domain is valid, false if it is not
    @jsondata:Name {value: "ValidDomain"}
    boolean validDomain?;
    # Telephone number of the address of the domain registrant
    @jsondata:Name {value: "RegistrantTelephone"}
    string registrantTelephone?;
    # City of the domain registrant, if available
    @jsondata:Name {value: "RegistrantCity"}
    string registrantCity?;
    # Street name of the address of the domain registrant, if available
    @jsondata:Name {value: "RegistrantStreet"}
    string registrantStreet?;
    # Street number of the address of the domain registrant, if available
    @jsondata:Name {value: "RegistrantStreetNumber"}
    string registrantStreetNumber?;
    # Country of the address of the domain registrant, if available
    @jsondata:Name {value: "RegistrantCountry"}
    string registrantCountry?;
    # Postal code of the address of the domain registrant, if available
    @jsondata:Name {value: "RegistrantPostalCode"}
    string registrantPostalCode?;
    # Name of the domain registrant
    @jsondata:Name {value: "RegistrantName"}
    string registrantName?;
    # State or Province of the address of the domain registrant, if available
    @jsondata:Name {value: "RegistrantStateOrProvince"}
    string registrantStateOrProvince?;
    # Raw address string of the domain registrant, if available
    @jsondata:Name {value: "RegistrantRawAddress"}
    string registrantRawAddress?;
    # Email address of the domain registrant
    @jsondata:Name {value: "RegistrantEmail"}
    string registrantEmail?;
    # WHOIS raw text record
    @jsondata:Name {value: "RawTextRecord"}
    string rawTextRecord?;
    # Organization name of the domain registrant
    @jsondata:Name {value: "RegistrantOrganization"}
    string registrantOrganization?;
};

# Result of validating a URL with full validation
public type ValidateUrlResponseFull record {
    # True if the URL has valid syntax, a valid domain, a valid endpoint, and passes virus scan checks; false otherwise
    @jsondata:Name {value: "ValidURL"}
    boolean validURL?;
    # True if the URL has valid syntax, false otherwise
    @jsondata:Name {value: "Valid_Syntax"}
    boolean validSyntax?;
    # True if the endpoint is up and responsive and passes a virus scan check, false otherwise
    @jsondata:Name {value: "Valid_Endpoint"}
    boolean validEndpoint?;
    # True if the domain name is valid and exists, false otherwise
    @jsondata:Name {value: "Valid_Domain"}
    boolean validDomain?;
    # Well-formed version of the URL
    @jsondata:Name {value: "WellFormedURL"}
    string wellFormedURL?;
};

# Input to a batch XXE detection operation
public type XxeDetectionBatchRequest record {
    # Multiple items to protect for XXE
    @jsondata:Name {value: "RequestItems"}
    XxeDetectionRequestItem[] requestItems?;
};

# Result of performing a IP threat check on an IP address
public type IPThreatResponse record {
    # Specifies the type of IP threat; possible values include Blocklist, Botnet, WebBot
    @jsondata:Name {value: "ThreatType"}
    string threatType?;
    # True if the input IP address is a threat, false otherwise
    @jsondata:Name {value: "IsThreat"}
    boolean isThreat?;
};

# Result of a first name validation operation
public type FirstNameValidationResponse record {
    # Possible values are: ValidFirstName, ValidUnknownFirstName, InvalidSpamInput, InvalidCharacters, InvalidEmpty
    @jsondata:Name {value: "ValidationResult"}
    string validationResult?;
    # True if the validation operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Identifier validation request, including the input identifier as well as various identifier rules
public type ValidateIdentifierRequest record {
    # True if whitespace is allowed in the identifier, false otherwise
    @jsondata:Name {value: "AllowWhitespace"}
    boolean allowWhitespace?;
    # Text string identifier input
    @jsondata:Name {value: "Input"}
    string input?;
    # True if numbers are allowed in the identifier, false otherwise
    @jsondata:Name {value: "AllowNumbers"}
    boolean allowNumbers?;
    # True if periods are allowed in the identifier, false otherwise
    @jsondata:Name {value: "AllowPeriods"}
    boolean allowPeriods?;
    # True if underscores are allowed in the identifier, false otherwise
    @jsondata:Name {value: "AllowUnderscore"}
    boolean allowUnderscore?;
    # True if hyphens are allowd in the identifier, false otherwise
    @jsondata:Name {value: "AllowHyphens"}
    boolean allowHyphens?;
    # Optional; minimum length, if any, of the identifier
    @jsondata:Name {value: "MinLength"}
    int:Signed32 minLength?;
    # Optional; maximum length, if any, of the identifier
    @jsondata:Name {value: "MaxLength"}
    int:Signed32 maxLength?;
};

# Syntactic validity of email address
public type AddressVerifySyntaxOnlyResponse record {
    # True if the email address is syntactically valid, false if it is not
    @jsondata:Name {value: "ValidAddress"}
    boolean validAddress?;
    # True if the email domain name is a free provider (typically a free to sign up web email provider for consumers / personal use), false otherwise
    @jsondata:Name {value: "IsFreeEmailProvider"}
    boolean isFreeEmailProvider?;
    # Domain name of the email address
    @jsondata:Name {value: "Domain"}
    string domain?;
    # True if the email address is a disposable email address, false otherwise; these disposable providers are not typically used to receive email and so will have a low likelihood of opening mail sent there
    @jsondata:Name {value: "IsDisposable"}
    boolean isDisposable?;
};

# Result of performing an XSS protection operation
public type XssProtectionResult record {
    # Normalized string result, with XSS removed
    @jsondata:Name {value: "NormalizedResult"}
    string normalizedResult?;
    # True if the input contained XSS scripting, false otherwise
    @jsondata:Name {value: "ContainedXss"}
    boolean containedXss?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Original input string
    @jsondata:Name {value: "OriginalInput"}
    string originalInput?;
};

# Result of checking a URL for safety threats
public type UrlSafetyCheckResponseFull record {
    # True if the URL is clean, false if it is at risk of containing a safety threat or attack
    @jsondata:Name {value: "CleanURL"}
    boolean cleanURL?;
    # Threat type identified, if any; possible values are "ForcedDownload", "VirusesAndMalware", "Phishing"
    @jsondata:Name {value: "ThreatType"}
    string threatType?;
};

# Request to determine if a URL is a Phishing threat
public type PhishingCheckRequest record {
    # URL to validate
    @jsondata:Name {value: "URL"}
    string uRL?;
};

# Result of validating a street address
public type NormalizeAddressResponse record {
    # True if the address is valid, false otherwise
    @jsondata:Name {value: "ValidAddress"}
    boolean validAddress?;
    # The name of the building, house or structure if applicable, such as "Cloudmersive Building 2".  This will often by null
    @jsondata:Name {value: "Building"}
    string building?;
    # The state or province of the address
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # The street number or house number of the address.  For example, in the address "1600 Pennsylvania Avenue NW" the street number would be "1600".  This value will typically be populated for most addresses
    @jsondata:Name {value: "StreetNumber"}
    string streetNumber?;
    # The name of the street or road of the address.  For example, in the address "1600 Pennsylvania Avenue NW" the street number would be "Pennsylvania Avenue NW"
    @jsondata:Name {value: "Street"}
    string street?;
    # The postal code or zip code of the address
    @jsondata:Name {value: "PostalCode"}
    string postalCode?;
    # Country of the address, if present in the address.  If not included in the address it will be null
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # If the address is valid, the degrees latitude of the validated address, null otherwise
    @jsondata:Name {value: "Latitude"}
    decimal latitude?;
    # The city of the address
    @jsondata:Name {value: "City"}
    string city?;
    # Two-letter ISO 3166-1 country code
    @jsondata:Name {value: "ISOTwoLetterCode"}
    string iSOTwoLetterCode?;
    # If the address is valid, the degrees longitude of the validated address, null otherwise
    @jsondata:Name {value: "Longitude"}
    decimal longitude?;
};

# Request to Validate a State or Province in a country
public type ValidateStateRequest record {
    # Required: State or province of the address to validate, such as 'California' or 'CA'
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # Optional (recommended); Name of the country, such as 'United States'.  If left blank, and CountryCode is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # Optional; two-letter country code (Two-letter ISO 3166-1 country code) of the country.  If left blank, and CountryFullName is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
};

# Result of performing SSRF threat checks on multiple URLs
public type UrlSsrfResponseBatch record {
    # Results of the operation, with indexes matched to input values
    @jsondata:Name {value: "OutputItems"}
    UrlSsrfResponseFull[] outputItems?;
};

# Individual item to protect for XSS
public type XssProtectionRequestItem record {
    # Individual input text item to protect from XSS
    @jsondata:Name {value: "InputText"}
    string inputText?;
};

# Result of validating a postal code
public type ValidatePostalCodeResponse record {
    # If valid; State or province corresponding to the input postal code, such as 'CA' or 'California'
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # If the postal code is valid, the degrees latitude of the centroid of the postal code, null otherwise
    @jsondata:Name {value: "Latitude"}
    decimal latitude?;
    # If valid, City corresponding to the input postal code, such as 'Walnut Creek'
    @jsondata:Name {value: "City"}
    string city?;
    # If the postal code is valid, the degrees longitude of the centroid of the postal code, null otherwise
    @jsondata:Name {value: "Longitude"}
    decimal longitude?;
    # True if the Postal Code is valid, false otherwise
    @jsondata:Name {value: "ValidPostalCode"}
    boolean validPostalCode?;
};

# Result of performing an Admin Path operation
public type IsAdminPathResponse record {
    # True if the input IP address is an Admin Path, and false otherwise
    @jsondata:Name {value: "IsAdminPathNode"}
    boolean isAdminPathNode?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# The result of a User-Agent validation request
public type UserAgentValidateResponse record {
    # Operating System of the User-Agent (e.g. Windows)
    @jsondata:Name {value: "OperatingSystem"}
    string operatingSystem?;
    # Model name or number of the User-Agent
    @jsondata:Name {value: "DeviceModel"}
    string deviceModel?;
    # Name of the Browser
    @jsondata:Name {value: "BrowserName"}
    string browserName?;
    # True if the request is a known robot, false otherwise
    @jsondata:Name {value: "IsBot"}
    boolean isBot?;
    # The version of the operating system of the User-Agent (e.g. "10" for Windows 10)
    @jsondata:Name {value: "OperatingSystemVersion"}
    string operatingSystemVersion?;
    # Brand name of the User-Agent
    @jsondata:Name {value: "DeviceBrandName"}
    string deviceBrandName?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Version of the Browser Engine
    @jsondata:Name {value: "BrowserEngineVersion"}
    string browserEngineVersion?;
    # Device type of the User-Agent; possible values are "DESKTOP", "SMARTPHONE", "TABLET"
    @jsondata:Name {value: "DeviceType"}
    string deviceType?;
    # The CPU platform of the User-Agent (e.g. x64)
    @jsondata:Name {value: "OperatingSystemCPUPlatform"}
    string operatingSystemCPUPlatform?;
    # Optional; if available, the URL to the robot
    @jsondata:Name {value: "BotURL"}
    string botURL?;
    # Name of the Browser Engine
    @jsondata:Name {value: "BrowserEngineName"}
    string browserEngineName?;
    # Version of the Browser
    @jsondata:Name {value: "BrowserVersion"}
    string browserVersion?;
    # Optional; name of the robot if the request was from a known robot, otherwise null
    @jsondata:Name {value: "BotName"}
    string botName?;
};

# Request to determine if a URL is valid
public type ValidateUrlRequestSyntaxOnly record {
    # URL to validate
    @jsondata:Name {value: "URL"}
    string uRL?;
};

# Input parameter to a country validation request
public type ValidateCountryRequest record {
    # Raw country input - can be a two-letter code (FIPS 10-4 or ISO 3166-1), three-letter code (ISO 3166-1) or country name
    @jsondata:Name {value: "RawCountryInput"}
    string rawCountryInput?;
};

# Request to reverse geocode a Street Address
public type ReverseGeocodeAddressRequest record {
    # Latitude coordinate in WGS84 format
    @jsondata:Name {value: "Latitude"}
    decimal latitude?;
    # Longitude coordinate in WGS84 format
    @jsondata:Name {value: "Longitude"}
    decimal longitude?;
};

# Result of validating a street address
public type ValidateAddressResponse record {
    # True if the address is valid, false otherwise
    @jsondata:Name {value: "ValidAddress"}
    boolean validAddress?;
    # If the address is valid, the degrees latitude of the validated address, null otherwise
    @jsondata:Name {value: "Latitude"}
    decimal latitude?;
    # If the address is valid, the degrees longitude of the validated address, null otherwise
    @jsondata:Name {value: "Longitude"}
    decimal longitude?;
};

# Details of one country
public type CountryDetails record {
    # Subregion in which the country is located; possible values are None, NorthernEurope, WesternEurope, SouthernEurope, EasternEurope, CentralAmerica, NorthernAmerica, SouthAmerica, EasternAfrica, MiddleAfrica, NorthernAfrica , SouthernAfrica , WesternAfrica , CentralAsia , EasternAsia , SouthernAsia , SouthEasternAsia , WesternAsia , Southern , Middle , AustraliaandNewZealand , Melanesia , Polynesia , Micronesia , Caribbean,
    @jsondata:Name {value: "Subregion"}
    string subregion?;
    # ISO 4217 currency three-letter code associated with the country
    @jsondata:Name {value: "ISOCurrencyCode"}
    string iSOCurrencyCode?;
    # Name of the country
    @jsondata:Name {value: "CountryName"}
    string countryName?;
    # Full name of the currency
    @jsondata:Name {value: "CurrencyEnglishName"}
    string currencyEnglishName?;
    # Region (continent) in which the country is located; possible values are None, Europe, Americas, Asia, Africa, Oceania
    @jsondata:Name {value: "Region"}
    string region?;
    # Three-letter ISO 3166-1 country code
    @jsondata:Name {value: "ThreeLetterCode"}
    string threeLetterCode?;
    # Two-letter ISO 3166-1 country code
    @jsondata:Name {value: "ISOTwoLetterCode"}
    string iSOTwoLetterCode?;
    # True if this country is currently a member of the European Union (EU), false otherwise
    @jsondata:Name {value: "IsEuropeanUnionMember"}
    boolean isEuropeanUnionMember?;
    # Symbol associated with the currency
    @jsondata:Name {value: "CurrencySymbol"}
    string currencySymbol?;
};

# Request to Validate a Street Address
public type ValidateAddressRequest record {
    # Required; Street address to validate, such as '2950 Buskirk Ave.'
    @jsondata:Name {value: "StreetAddress"}
    string streetAddress?;
    # Required; State or province of the address to validate, such as 'CA' or 'California'
    @jsondata:Name {value: "StateOrProvince"}
    string stateOrProvince?;
    # Optional (recommended); Zip code or postal code of the address to validate, such as '94597'
    @jsondata:Name {value: "PostalCode"}
    string postalCode?;
    # Optional (recommended); Name of the country, such as 'United States'.  If left blank, and CountryCode is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryFullName"}
    string countryFullName?;
    # Required; City part of the addrerss to validate, such as 'Walnut Creek'
    @jsondata:Name {value: "City"}
    string city?;
    # Optional; two-letter country code (Two-letter ISO 3166-1 country code) of the country.  If left blank, and CountryFullName is also left blank, will default to United States.  Global countries are supported
    @jsondata:Name {value: "CountryCode"}
    string countryCode?;
};
